- CLAUDE.md
- scripts/clean-project.sh
Implements a cleanup script and establishes project maintenance guidelines to keep the repository clean and organized.
- ✨ Created `scripts/clean-project.sh` to automate cleanup of system files
- 📝 Updated CLAUDE.md with maintenance commands and cleanliness guidelines
- 🗑️ Removed empty mockups directory at root level
- 🧹 Cleaned all .DS_Store files from the repository
The new cleanup script (`scripts/clean-project.sh`) handles:
- Removal of .DS_Store and other macOS system files
- Removal of Windows system files (Thumbs.db, desktop.ini)
- Removal of editor swap files (.swp, .swo, ~)
- Cleanup of empty directories (excluding node_modules, .git, dist, build)
- Reporting on potentially problematic files (logs, backups, archives)
Added new section to CLAUDE.md:
- Project Maintenance & …
> feat: add project cleanup script and maintenance guidelines

- CLAUDE.md
This PR enhances CLAUDE.md with comprehensive improvements based on exhaustive analysis of all GitHub issues and pull requests in the project.
- Analyzed **64+ GitHub issues** to identify recurring error patterns
- Reviewed **63 pull requests** to understand common implementation mistakes
- Researched **2025 best practices** for AI coding assistants
- 25% of issues were related to React hydration errors
- 20% involved repository bloat/file management problems
- 20% were multilingual implementation issues
- Multiple PRs required revisions or failed entirely (e.g., 3 failed dark mode attempts)
- Concrete examples of what NOT to do
- Correct patterns with code examples
- Prevents the most common hydration errors
- Clear table showing when to use `.astro` vs `.tsx`
- Eliminates architectural …
> feat: enhance CLAUDE.md with comprehensive improvements

- .github/path-filters.yml
- .github/workflows/codeql.yml
- .github/workflows/nightly-tests.yml
- .github/workflows/pr-tests.yml
- README.md
- docs/decisions/issue-77-implementation.md
- docs/decisions/issue-77-pr-test-optimizations.md
- docs/how-to/nightly-tests.md
- phialo-design/.gitignore
- phialo-design/.lighthouserc.json
- phialo-design/docs/how-to/run-pr-tests.md
- phialo-design/package.json
- phialo-design/playwright.config.pr.ts
- phialo-design/playwright.config.ts
- phialo-design/playwright.nightly.config.ts
- phialo-design/playwright.pr.config.ts
- phialo-design/pnpm-lock.yaml
- phialo-design/scripts/run-nightly-tests.sh
- phialo-design/scripts/test-pr-local.sh
- phialo-design/scripts/test-pr.sh
- phialo-design/src/shared/navigation/LanguageSelector.astro
- phialo-design/tests/e2e/contact-form.spec.ts
- phialo-design/tests/e2e/critical-tests-example.spec.ts
- phialo-design/tests/e2e/critical-tests-example.spec.ts.example
- phialo-design/tests/e2e/integration.spec.ts
- phialo-design/tests/e2e/landing-page.spec.ts
- phialo-design/tests/e2e/navigation.spec.ts
- phialo-design/tests/e2e/portfolio-comprehensive.spec.ts
- phialo-design/tests/e2e/responsive.spec.ts
This PR implements comprehensive optimizations to reduce PR test execution time from 30-40 minutes to 10-15 minutes while maintaining test quality through a "minimal core + nightly full suite" strategy.
- **Path-based filtering**: Tests only run when relevant files change
- **Node.js matrix reduction**: From 3 versions (18.x, 20.x, 22.x) to single version (20.x)
- **Parallel E2E execution**: Increased workers from 1 to 4 for faster test runs
- **Browser matrix optimization**: Reduced to Chrome, Firefox, iOS Safari, Android Chrome for PRs
- **Critical tests for PRs**: Added `@critical` tags to 15 essential E2E tests
- **Nightly comprehensive suite**: Full 80-test suite runs at 2 AM UTC with all browsers
- **Smart caching**: Playwright browsers and build artifacts are cached
- …
> feat: optimize PR test workflow to reduce execution time #77

- phialo-design/src/features/services/components/ServicesSection.astro
> Remove unused tutorialInfo2 from German content in ServicesSection.astro

- phialo-design/src/features/services/components/ServicesSection.astro
- **Remove unused tutorialInfo2 from German content in ServicesSection.astro**
- **Update ServicesSection.astro: Anpassungen an Tutorial-Text und Layout**
> remove tutorialInfo2

- .github/workflows/cleanup-preview.yml
- LICENSE-ASSETS
- LICENSE-CODE
- LICENSE.md
- NOTICE
- README.md
- phialo-design/package.json
- phialo-design/src/shared/navigation/Footer.astro
- phialo-design/tests/e2e/contact-form.spec.ts
- phialo-design/tests/e2e/navigation.spec.ts
- workers/package.json
- ✅ Established dual licensing structure: AGPLv3 for code, CC BY-NC-ND 4.0 for creative assets
- ✅ Added BrowserStack acknowledgment to README
- ✅ Updated copyright year to 2025 in Footer component
- **LICENSE.md**: Main file explaining the dual licensing approach
- **LICENSE-CODE**: References AGPLv3 for all source code
- **LICENSE-ASSETS**: Details CC BY-NC-ND 4.0 for creative assets with attribution requirements
- **README.md**: Added comprehensive license section and BrowserStack acknowledgment with logo
- **NOTICE**: Created third-party attributions file listing all major dependencies
- **package.json files**: Added `"license": "AGPL-3.0"` field to both main and workers packages
- **Footer.astro**: Updated copyright year from 2024 to 2025
- Ensures modifications remain open source
- …
> feat: add comprehensive licensing documentation (closes #131)

- docs/issues/issue-145-academy-authentication-booking/ACADEMY-AUTH-BOOKING-ANALYSIS.md
- docs/issues/issue-145-academy-authentication-booking/CALENDAR-SAAS-ADMIN-UPDATE.md
- docs/issues/issue-145-academy-authentication-booking/mockups/MOCKUP-DESCRIPTIONS.md
- docs/issues/issue-145-academy-authentication-booking/mockups/academy-admin-video-management.html
- docs/issues/issue-145-academy-authentication-booking/mockups/academy-authenticated-portal.html
- Preserved academy authentication and booking system documentation from the deleted `feature/dark-mode` branch
- These docs were unrelated to dark mode and should be kept in the project
The `feature/dark-mode` branch was deleted after the dark mode implementation failed (see issue #42). However, it contained valuable documentation for issue #145 (academy authentication and booking system) that needed to be preserved.
- Added `docs/issues/issue-145-academy-authentication-booking/` directory with:
- `ACADEMY-AUTH-BOOKING-ANALYSIS.md` - Comprehensive analysis of authentication and booking requirements
- `CALENDAR-SAAS-ADMIN-UPDATE.md` - Calendar SaaS integration details
- `mockups/` - HTML mockups and screenshots for the academy portal
- #42 - Dark mode implementation (failed, branch …
> Preserve academy docs from failed dark mode branch

- .github/workflows/cleanup-artifacts.yml
- .github/workflows/cloudflare-pr-cleanup.yml
- .github/workflows/cloudflare-pr-preview.yml
- phialo-design/src/shared/hooks/useLanguage.ts
This PR pushes the CodeQL security fixes that were already committed locally but not pushed to the remote repository.
- **File**: `phialo-design/src/shared/hooks/useLanguage.ts`
- **Issue**: Potential open redirect vulnerability
- **Fix**: Added `isValidPath()` function that validates all navigation URLs
- Prevents protocol-relative URLs, external URLs, and malicious paths
- **File**: `.github/workflows/cleanup-artifacts.yml`
- **Issue**: Missing permissions declaration
- **Fix**: Added `permissions: contents: read` to the summary job
- ✅ All `window.location.href` and `window.location.replace` calls now validated
- ✅ Blocks URLs with protocols (http://, javascript:, etc.)
- ✅ Prevents protocol-relative URLs (//example.com)
- ✅ Disallows @ character to prevent user info in URLs
- ✅ Only …
> Push CodeQL security fixes to remote

- CLAUDE.md
- phialo-design/src/features/services/components/ServicesSection.astro
- phialo-design/src/shared/navigation/Footer.astro
- phialo-design/src/shared/navigation/MobileMenu.tsx
- Centers all text elements within service cards for improved visual consistency
- Addresses the alignment issue shown in the screenshot from PR #184
- Specifically improves mobile view alignment as requested by @GesaP
- Changed tutorial section text from `text-left` to `text-center` class
- Added responsive ordering for tutorial section on mobile (image first, text second)
- Improved image responsiveness with proper width constraints on mobile devices
- Enhanced mobile viewing experience by ensuring all content is properly centered
- Tutorial section now stacks properly on mobile with image appearing first
- Images now have proper responsive width constraints (`w-full max-w-xs md:max-w-full`)
- All text content is consistently centered across all viewport sizes
Fixes #186
> Fix #186: Center text alignment in services section

- phialo-design/src/features/home/components/TestimonialsSection.astro
Replaced Marina Weber's testimonial with a real review from Noemie Böbs of Mare Schmuck, as requested in issue #199.
- Replaced German review text with: "Es ist eine Freude, mit Gesa Pickbrenner zusammenzuarbeiten. Sie ist sehr professional und kreativ. - ich habe bereits mehrere Kollektionen mit ihr umgesetzt."
- Updated English translation to: "Collaborating with Gesa Pickbrenner is a true pleasure. She is highly professional and creative, and I have already brought several collections to life with her."
- Updated author from "Marina Weber, Schmuckdesignerin" to "Noemie Böbs, Mare Schmuck"
- Updated date from "März 2023" to "Juli 2025"
Mare Schmuck is a family-owned jewelry business from Lübeck-Travemünde, Germany, operating since 1932. Noemie Böbs is associated with the business and …
> fix: replace Marina Weber review with Noemie Böbs review

- phialo-design/package.json
- phialo-design/pnpm-lock.yaml
- phialo-design/src/assets/images/portfolio-hero-bg.jpg
- phialo-design/src/features/portfolio/pages/en/index.astro
- phialo-design/src/features/portfolio/pages/index.astro
This PR implements a comprehensive portfolio hero section with a full-width background image and properly styled text overlays, addressing all requirements from issue #196.
- Plain gradient background
- Regular black text on light background
- Standard container width
- ✅ Full-width hero image (edge-to-edge, no whitespace)
- ✅ White text with 0.8px black outline for optimal readability
- ✅ Dark gradient overlay for text contrast
- ✅ Responsive design for all screen sizes
- Used Astro's `<Image>` component for optimized loading
- Set `loading="eager"` and `fetchpriority="high"` for above-the-fold content
- Configured WebP format with 85% quality for performance
- Proper width/height attributes to prevent layout shift
- Uses existing `/images/homepage/portfolio-feature.jpg` from public …
> Fix portfolio hero section formatting issue #196

- phialo-design/public/images/portfolio/castle_piggy_bank_2.jpg
- phialo-design/public/images/portfolio/castle_piggy_bank_3.jpg
- phialo-design/public/images/portfolio/castle_piggy_bank_4.jpg
- phialo-design/public/images/portfolio/castle_piggy_bank_5.jpg
- phialo-design/public/images/portfolio/castle_piggy_bank_6.jpg
- phialo-design/public/images/portfolio/castle_piggy_bank_7.jpg
- phialo-design/public/images/portfolio/castle_piggy_bank_8.jpg
- phialo-design/public/images/portfolio/castle_piggy_bank_9.jpg
- phialo-design/public/images/portfolio/silver_piggy_bank.jpg
- phialo-design/public/images/portfolio/winged-ring-1.jpg
- phialo-design/public/images/portfolio/winged-ring-2.jpg
- phialo-design/src/content/portfolio/silber-piggy-bank.md
- phialo-design/src/content/portfolio/silver-castle-coin-box-en.md
- phialo-design/src/features/contact/components/ContactFormWithPreClearance.test.tsx
- phialo-design/src/features/portfolio/data/portfolioDataDE.ts
- phialo-design/src/features/portfolio/data/portfolioDataEN.ts
This PR updates the "Silver Castle Piggy Bank" portfolio item according to the requirements in issue #294.
- ✅ Renamed to "Castle Piggy Bank" (EN) / "Münzkästchen in Form eines Schlosses" (DE)
- ✅ Updated description emphasizing the real castle transformation from Schleswig-Holstein
- ✅ Changed materials to "Sterling Silver" and "18kt Yellow Gold" 
- ✅ Added 8 new high-quality images to the gallery (9 total images now)
- ✅ Updated both German and English content versions
- ✅ Synchronized TypeScript data files with content collection changes
- ✅ Fixed import issue in ContactFormWithPreClearance test file
The portfolio item now displays with the updated title "Castle Piggy Bank" / "Münzkästchen in Form eines Schlosses" and includes all 9 new images in the gallery.
Closes #294
> feat: Update Castle Piggy Bank portfolio item #294

- phialo-design/public/images/3DfuerSie/3d-printing-casting-service.jpg
- phialo-design/src/features/contact/components/ContactForm.tsx
- phialo-design/src/features/contact/components/ContactFormErrorBoundary.tsx
- phialo-design/src/features/contact/components/ContactFormWithPreClearance.tsx
- phialo-design/src/features/services/components/ServicesSection.astro
- phialo-design/src/features/services/pages/index.astro
- phialo-design/src/shared/components/ui/LazyImage.tsx
- phialo-design/src/shared/layouts/PageLayout.astro
- phialo-design/src/styles/global.css
This PR addresses all React hydration errors and implements comprehensive accessibility improvements as outlined in issue #271.
- **Prevented FOUC (Flash of Untranslated Content)**: Added `isHydrated` state to all components with language-dependent rendering
- **Fixed components**:
- `ContactForm.tsx`: Prevents rendering until language is determined client-side
- `ContactFormWithPreClearance.tsx`: Same hydration guard pattern
- `ContactFormErrorBoundary.tsx`: Delays error UI rendering until hydrated
- `LazyImage.tsx`: Conditionally renders quality badge after hydration
- **Impact**: Eliminates hydration mismatches between server and client renders
- Updated global `:focus-visible` styles to use consistent gold outline (#D4A259)
- Removed conflicting focus utilities from buttons and form …
> Fix: Resolve hydration errors and improve accessibility (#271)

- phialo-design/public/bartholomaeus-portrait.jpg
- phialo-design/src/features/about/pages/en/index.astro
- phialo-design/src/features/about/pages/index.astro
- phialo-design/src/shared/navigation/Footer.astro
- phialo-design/src/shared/navigation/Navigation.tsx
This PR adds Bartholomäus Dedersen to the About page, acknowledging his important role as Co-Founder & IT partner at Phialo Design. The implementation includes a dedicated team section that highlights his contributions to IT infrastructure, creative collaboration, and strategic partnership.
Closes #299
- **German Version**: Added "Unser Team" section with Bartholomäus's information
- Name: Bartholomäus Dedersen
- Role: Co-Founder & IT
- Responsibilities: Strategic partner, IT infrastructure management, creative collaboration, artistic consulting
- GitHub profile link
- **English Version**: Added "Our Team" section with translated content
- Consistent information and structure as German version
- Properly translated role descriptions
- Added responsive team member section below Gesa's …
> feat: Add Bartholomäus Dedersen to About Page as Co-Founder & IT

- phialo-design/.gitattributes
- phialo-design/public/bartholomaeus-portrait-alt.jpg
- phialo-design/public/gesa-portrait-alt.jpg
- phialo-design/src/features/about/components/TeamMemberImage.tsx
- phialo-design/src/features/about/pages/en/index.astro
- phialo-design/src/features/about/pages/index.astro
This PR implements interactive Easter egg hover effects for the team member portraits on the About page, adding a delightful surprise for visitors who discover them. When users hover over the portraits, they reveal fun alternative photos - a swan photo for Bartholomäus and an alternate portrait for Gesa.
- ✨ Created new `TeamMemberImage` React component with sophisticated hover effects
- 🖼️ Added alternative portrait images for both team members
- ♿ Implemented full keyboard accessibility (Enter/Space to toggle)
- 🎨 Added subtle visual hint (eye icon) that appears on hover
- ⚡ Optimized performance with image preloading for seamless transitions
- 🌐 Updated both German and English About pages
- **Hydration-Safe**: Properly handles SSR/hydration with `useState`/`useEffect` pattern
- …
> feat: Add Easter egg hover effects for team portraits #307

- .github/workflows/notify-issue-owner.yml
- phialo-design/playwright.browserstack.config.ts
- phialo-design/playwright.shard.config.ts
- phialo-design/scripts/performance-tests.js
- phialo-design/src/features/classes/components/ClassesSection.astro
- phialo-design/src/features/contact/components/ContactFormErrorBoundary.tsx
- phialo-design/src/features/contact/components/ContactFormUnified.tsx
- phialo-design/src/features/contact/components/ContactFormWithPreClearance.test.tsx
- phialo-design/src/features/contact/components/TurnstileWidget.tsx
- phialo-design/src/features/legal/pages/en/privacy.astro
- phialo-design/src/features/legal/pages/privacy.astro
- phialo-design/src/features/services/components/ServicesSection.astro
- phialo-design/tailwind.config.mjs
- phialo-design/tests/e2e/landing-page.spec.ts
This PR fixes critical TypeScript errors that were causing GitHub Actions failures, particularly in the Manual Cloudflare Deployment workflow.
- ✅ Fixed Playwright configs (browserstack and shard) - resolved 'browserstack:options' type issues
- ✅ Fixed ContactFormUnified and TurnstileWidget components - removed unsupported props
- ✅ Fixed ContactFormWithPreClearance tests - corrected React context usage
- ✅ Fixed ClassesSection.astro - added null checks and removed unused imports
- ✅ Fixed privacy pages - proper window property access with type casting
- ✅ Fixed ServicesSection.astro - added HTMLElement type casting
- ✅ Fixed e2e test type annotations in landing-page.spec.ts
- ✅ Fixed Notify Issue Owner workflow to properly handle check_suite events
- 🧹 Removed unused imports and …
> Fix: Resolve critical TypeScript errors and workflow issues

- workers/src/router/handlers/redirect.ts
Die deutsche Kontaktseite (phialo.de/contact/) führte zu einem 404-Fehler, weil der Worker trailing slashes von allen URLs entfernt hat.
Astro generiert Seiten als Verzeichnisse mit index.html Dateien (z.B. `/contact/index.html`). Der Worker hatte eine Regel, die trailing slashes von allen URLs entfernt (außer root), was dazu führte, dass `/contact/` zu `/contact` redirected wurde. Dies verursachte 404-Fehler.
- Liste von Pfaden hinzugefügt, die ihre trailing slashes behalten sollen (alle Astro-Routen)
- Redirect-Handler modifiziert, um das Entfernen von trailing slashes für diese Pfade zu überspringen
- Verhindert unnötige Redirects, die den direkten Zugriff auf Seiten verhinderten
Lokal getestet:
- ✅ `/contact/` gibt 200 OK zurück (kein Redirect)
- ✅ `/contact` wird zu `/contact/` …
> Fix: Preserve trailing slashes for Astro directory routes

- README.md
Updated link in Readme.MD for eglibility of BrowserStack sponsorship.
> Update README.md for Browserstack Sponsorship

- .github/actions/deploy-worker/action.yml
- .github/workflows/cloudflare-pr-preview.yml
- .github/workflows/deploy-command.yml
- .github/workflows/docker-pr-builds.yml.disabled
- .github/workflows/manual-deploy.yml
- .github/workflows/nightly-tests.yml
- .github/workflows/webhook-deploy.yml
- README.md
- phialo-design/docs/how-to/ENVIRONMENT-SETUP-GUIDE.md
This PR fixes the Cloudflare Web Analytics integration issue (#350) and implements comprehensive Infrastructure as Code improvements for all deployment workflows.
1. **Analytics not working**: Analytics data wasn't showing on https://phialo-master.meise.workers.dev/ because deployment workflows weren't passing `PUBLIC_CLOUDFLARE_ANALYTICS_TOKEN` during build time.
2. **Environment variables scattered**: All environment variables and secrets were duplicated across 5 different workflow files, violating DRY principles.
3. **Lefthook warnings**: Git commits showed "Can't find lefthook in PATH" warnings due to missing setup documentation.
Created 3 composite GitHub Actions for centralized configuration:
- **`build-astro`**: Manages all PUBLIC_* build-time variables
- **`setup-environment`**: …
> Fix: Cloudflare Analytics integration and comprehensive IaC improvements

- package-lock.json
- phialo-design/LIGHTHOUSE_COMPARISON.md
- phialo-design/src/features/portfolio/components/OptimizedPortfolioGrid.tsx
- phialo-design/src/shared/layouts/MobileOptimizedLayout.astro
- phialo-design/src/styles/global.css
- phialo-design/src/styles/mobile-optimizations.css
- phialo-design/src/utils/adaptive-loading.ts
- phialo-design/src/utils/deferred-loading.ts
This PR implements comprehensive mobile performance optimizations to achieve performance parity between mobile and desktop experiences, addressing issue #359.
- **Adaptive Loading System**: Network-aware and device-capability-aware content delivery
- **Mobile-Optimized CSS**: Touch targets, reduced motion support, and performance optimizations
- **Deferred JavaScript Loading**: Smart deferral of non-critical scripts on mobile devices
- **Resource Hints Strategy**: Mobile-specific preloading and prefetching strategies
- **Optimized Portfolio Grid**: Enhanced lazy loading with touch gesture support
- `src/utils/adaptive-loading.ts` - Network/device detection and adaptive strategies
- `src/utils/deferred-loading.ts` - JavaScript deferral and lazy component loading
- …
> fix: Implement comprehensive mobile performance optimizations (#359)

- docs/decisions/compression-caching-improvements.md
- phialo-design/astro.config.mjs
- phialo-design/package.json
- phialo-design/pnpm-lock.yaml
- phialo-design/public/_headers
- scripts/configure-compression.sh
- workers/src/handlers/assets-modern.ts
- workers/src/middleware/cache.ts
- workers/wrangler.toml
This PR implements advanced compression (Brotli) and fine-tuned caching strategies to reduce payload sizes and improve repeat visit performance, addressing Lighthouse findings from issue #358.
- Added `vite-plugin-compression` to generate `.gz` and `.br` files during build
- Brotli compression at maximum quality (level 11)
- Only compresses files >1KB to avoid overhead
- Updated asset handler to serve pre-compressed files based on Accept-Encoding
- Added proper Vary headers for cache keying
- Fallback chain: Brotli → Gzip → Uncompressed
- Enhanced cache middleware with SWR support
- Serves stale content instantly while revalidating in background
- Adds diagnostic headers for debugging (X-Cache-State, X-Cache-Revalidate)
- Immutable caching for hashed assets (1 year)
- SWR for images and …
> 🗜️ Implement comprehensive compression and caching improvements (#358)

- phialo-design/public/manifest.json
- phialo-design/public/sw.js
- phialo-design/src/pages/offline.astro
- phialo-design/src/shared/components/ServiceWorkerRegistration.astro
- phialo-design/src/shared/layouts/BaseLayout.astro
This PR implements a comprehensive service worker for the Phialo Design website to enable offline functionality, improve performance on repeat visits, and achieve PWA capabilities.
- **Intelligent Caching Strategies**:
- Cache-first for images and static assets (fonts, favicon)
- Network-first with cache fallback for HTML pages
- Stale-while-revalidate for CSS/JS resources
- Automatic cache versioning and cleanup
- **Offline Support**:
- Beautiful offline fallback page with multilingual support (German/English)
- Auto-reload when connection is restored
- Cached page availability detection
- **Update Notifications**:
- Automatic detection of new service worker versions
- User-friendly update prompts with multilingual text
- Skip waiting functionality for immediate updates
- **Performance …
> 🔧 [Lighthouse] Service Worker Implementation for Offline & Caching (#356)

- .github/workflows/cloudflare-garbage-collection.yml
- .github/workflows/cloudflare-pr-cleanup.yml
This PR fixes the critical issue where PR preview deployments (Cloudflare Workers) were not being automatically deleted after PRs were merged, resulting in orphaned workers accumulating in the Cloudflare account.
The cleanup workflow had a hard dependency on the `preview-deployed` label, which caused orphaned workers when:
- Label addition failed after deployment
- The cached workflow didn't add labels
- Race conditions occurred between deployment and labeling
- The cleanup workflow now **always** attempts cleanup when a PR closes
- No longer relies on the brittle `preview-deployed` label
- Implements direct API calls for worker deletion (since wrangler doesn't have a delete command)
- Multiple fallback strategies for maximum reliability
- Comprehensive error handling and logging
- New …
> fix(ci): Remove label dependency and implement robust PR cleanup (#404)
